### ISSUE TITLE
開催頻度どのくらいが適切?

### ISSUE THREAD

**Issue by kanayannet** [gunmaweb/voluntary_association#3]
- 従来予定している隔月開催を行えるようにしたい。
  - 例:偶数月(or奇数月)の第xx土曜日に開催にする?
  - 例：アンケートを事前に取っても結構直前にならないと解らないのでは？
  - 会場を抑えるのも実は時期が決まっていた方が楽。

**Comment by clicktx** [comment]
個人的には3ヶ月ペースがちょうどいいかな、と感じています。
#6 のようなスピンオフ的な会を挟めますし。
- 1,4,7,10月
- 2,5,8,11月
- 3,6,9,12月

1月と12月を避けるならば 2月からのペースでしょうか。避ける必要があるかどうかは分かりませんが...。

**Comment by kanayannet** [comment]
> 1月12月を避ける
> この月でなくても避けた方が良い期間はありそうですね。
> 決算月、青色申告、お盆、正月、クリスマス、年末(12月27-29日以降)
> ありがとうございます！

**Comment by kanayannet** [comment]
年3回もありでは?案。
その間にもう少し別のイベントをやる。

**Comment by kanayannet** [comment]
次回1月第３週土曜日その後、３ヶ月後の第３土曜日で開催とする。
